dataset: "BGL"
win_size: 100
demo_max_windows: 400
data_seq_len: 10
input_c: 10
batch_size: 64
data_path: "data/BGL"
output_dir: "outputs/bgl"
threshold_output: "outputs/bgl/thresholds_edge.yaml"

routing_tolerance: 0.1
routing_distance: "ma"

edge_models:
  - name: "qbat_e3_k4_l3_b32"
    checkpoint: "checkpoints/qbat/bgl/BGL_e3_k4_l3_b32.pte"
  - name: "qbat_e3_k5_l3_b96"
    checkpoint: "checkpoints/qbat/bgl/BGL_e3_k5_l3_b96.pte"
  - name: "qbat_e6_k4_l3_b64"
    checkpoint: "checkpoints/qbat/bgl/BGL_e6_k4_l3_b64.pte"

cloud:
  model_save_path: "checkpoints/bat/bgl"
  thresholds_yaml: "outputs/bgl/thresholds_cloud.yaml"
  voting: "majority"
  num_epochs: [3, 6, 10]
  k: [3, 4, 5]
  e_layer_num: [3, 6, 8]
  batch_size: [32, 64, 96]
