lr: 0.0001
win_size: 100
data_seq_len: 10
input_c: 10
output_c: 10
dataset: "BGL"
mode: "train"
data_path: "data/BGL"
model_save_path: "checkpoints/bat/bgl"

num_epochs: [3, 6, 10]
k: [3, 4, 5]
e_layer_num: [3, 6, 8]
batch_size: [32, 64, 96]
